services:
  server:
    build:
      target: dev
      args:
        - NODE_ENV=dev
    environment:
      - NODE_ENV=dev #the app will spin up the target env variables
    env_file:
      - .env.dev
    ports:
      - 8087:8087
    user: 'appuser:appgroup'
    volumes:
      - ./src:/usr/app/src/

  sql-db:
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mv-task
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    ports:
      - 6380:6379
    volumes:
      - cache_data:/data

volumes:
  postgres_data: #/var/lib/docker/volumes/postgres_data/_data
  cache_data: #/var/lib/docker/volumes/cache_data/_data
