name: cd-workflow

on:
  workflow_run:
    workflows: ['ci-workflow']
    types: [completed]
    branches:
      - mucho
      - dev
  workflow_dispatch:

jobs:
  setup: #The workflow must contain at least one job with no dependencies.
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Setting up deployment..."

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PASS: ${{ secrets.SSH_PASS }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Verify SSH Connectivity
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'echo "SSH Connection Successful"'

      - name: Install sshpass # runner may not have ssh-pass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd ~/app/server-networks/ && echo $SSH_PASS | sudo -S ./deploy.dev.sh"
